### PR TITLE
Increase Carbon ad revenue by 30%

### PR DESCRIPTION
**Pull request by bvallelunga**
Hey @rohitrango,

Awesome choice picking Carbon ads, they are simple and unobtrusive! My friend and I have been working on our spare time a way to increase Carbon revenue by ~30%. 

We realized that ad blockers were taking a huge chunk of our revenue so we built [Miza](https://miza.io). You can think of Miza as a body guard for your ads, when Miza is installed, your ads will always appear.

We are currently in a private beta and thought your site would be a great fit! If you want to give us a, it's as simple as merging the pull request. Once you have merged the pull request you can view your analytics with this link: [http://miza.io/invite/eywxsc](http://miza.io/invite/eywxsc)

You can contact me directly if you have any questions at brian@miza.io Thanks for your time!

### CODE REVIEW

**Comment by rohitrango** [comment]
Thanks for your suggestion @bvallelunga 
But at the moment I'm not accepting any PRs. I hope you understand. Thanks! :smile:

**Comment by bvallelunga** [comment]
Sure @rohitrango. Based on startbootstrap.com web traffic, I am sure Miza could generate ~400k more impressions per month. Would you mind taking a look at Miza?

**Comment by rohitrango** [comment]
Sure! @bvallelunga

**Comment by bvallelunga** [comment]
@rohitrango Awesome! If you decide to give us a try, you can create an account with this link: http://miza.io/invite/eywxsc

**Pull request closed without merging**
